apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
spec:
  instances: 1

  http:
    httpEnabled: true

  db:
    vendor: postgres
    host: postgres-db
    database: keycloak
    usernameSecret:
      name: keycloak-db-secret
      key: username
    passwordSecret:
      name: keycloak-db-secret
      key: password

  hostname:
    hostname: keycloak-service-kafka.apps.ldossant.vmware.tamlab.rdu2.redhat.com

  proxy:
    headers: xforwarded
